### ISSUE TITLE
Shortcut not working within Commit-Dialog

### ISSUE THREAD

**Issue by Maybach91** [AutismSuperman/git-commit-message-helper#2]
I use the Phpstorm Shortcut CMD+K to open the commit dialog. I set a Shortcut for open the Commit Message Helper. But its not working. Neither in the Dialog nor in the normal Phpstorm environment. I have set `CTRL+ALT+K` (no conflicts) as Shortcut.

![image](https://user-images.githubusercontent.com/1867543/72910358-b7d6ec00-3d38-11ea-91bb-0f0919636500.png)

**Comment by tad3j** [comment]
I just installed it and it works OK on Windows 10. Maybe external software is capturing that key press sequence?

**Comment by HonLuk** [comment]
same problem in macos
