### ISSUE TITLE
建议类型名称能使用完整单词应该使用完整的写法

### ISSUE THREAD

**Issue by youngledo** [AutismSuperman/git-commit-message-helper#22]
![image](https://github.com/AutismSuperman/git-commit-message-helper/assets/68590897/bb7d25f0-b630-4f97-afd6-709d70f846da)
比如feature，没必要写成feat、performance没必要写成perf。

**Comment by UnclePi979** [comment]
这是大多数模版的规范，可以参考下这个：https://alndaly.github.io/docs/others/Github/standard/

另外，作者还提供了自定义`Type of Change` 的功能。你可以在IDEA的这个位置修改：
`Settings > Other Settings > GitCommitMessageHelper > Commit Template > Type`

![image](https://github.com/user-attachments/assets/025b4ac7-e58e-4d9e-a387-c4b21dbf24a4)
